name = "RadioAstroTools"
uuid = "041066b3-17c0-4d0d-9509-9cd497d75680"
authors = ["Haoran-Feng <hrfeng@pmo.ac.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
